### PR TITLE
Capitalization of Api => API

### PR DESCRIPTION
**Pull request by hisRoyalty**
Just a small typo.

### CODE REVIEW

**Comment by pgamerx** [comment]
Maybe make a single PR with all the small changes instead of different PRs for different small changes

**Comment by hisRoyalty** [comment]
Yes, and sorry, you closed the last PR.

**Comment by pgamerx** [comment]
> Yes, and sorry, you closed the last PR.

Which PR?

**Comment by pgamerx** [comment]
Oh, Adib's one? I just copied/pasted the code because there were conflicts

**Comment by pgamerx** [comment]
Anyway

**Comment by Adib-C** [comment]
> Oh, Adib's one? I just copied/pasted the code because there were conflicts

you can resolve the conflict -> https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github

**Comment by pgamerx** [comment]
> > Oh, Adib's one? I just copied/pasted the code because there were conflicts
> 
> you can resolve the conflict -> https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github

Thanks, but there isn't a need anymore because I already copied your code and pasted it lol

**Pull request merged**
