### PR TITLE
Fixing the likes and dislikes bar

### PR DESCRIPTION
**Pull request by Adib-C**
The previous bar doesn't show the actual percentage of the likes and dislikes because @pgamerx used the `innerText` of the like button which can be `2.1k`, which is not a number, and the `addBar()` function needs a number, so i fixed it for you :D

### CODE REVIEW

**Comment by hisRoyalty** [comment]
+1

**Comment by pgamerx** [comment]
Let me see

**Review by pgamerx — CHANGES_REQUESTED** [review]
```js
        .querySelector(
          "ytd-menu-renderer.ytd-video-primary-info-renderer > div > :nth-child(1) yt-formatted-string"
        )
        .ariaLabel.replace(/[^\d-]/g, "");
        ```
        
        Wouldn't it return 1.99k as 1.99?

**Comment by Adib-C** [comment]
No, since the `ariaLabel` of the like button is the exact number of the likes, example : 3,052,561 which is displayed as 3M likes in the page

**Comment by pgamerx** [comment]
@Adib-C , @hisRoyalty 
I fixed it using a much simple way in https://github.com/pgamerx/yt-dislikes-viewer/commit/ac297466032fdcce85a752e025abba1d91626a69

**Comment by Adib-C** [comment]
i don't think that is much simpler, but if it works, it works

**Comment by hisRoyalty** [comment]
^

**Comment by pgamerx** [comment]
Mine doesn't seem to work, idk why

**Comment by Adib-C** [comment]
try mine, it works

**Pull request closed without merging**
