### PR TITLE
Adding webstore submission workflow

### PR DESCRIPTION
**Pull request by louisgv**
Hi @pgamerx,

Love this extension! I was looking for ways to contribute, and thought adding a bit more ci might help. This PR introduces a new github action workflow that uses [download-release-asset](https://github.com/plasmo-corp/download-release-asset) to download the latest release assets, and  [bpp](https://browser.market) to automatically submit the zip files to various extension stores. The action is set to run manually from the github action tab, but we can tweak it to run as frequent as needed! The only thing you would need to create is a `SUBMIT_KEYS` github repository secret.

This secret is a json, with the schema defined [here](https://github.com/plasmo-corp/bpp/blob/main/keys.schema.json).

Here's a sample key for you:

```json
{
  "$schema": "https://raw.githubusercontent.com/plasmo-corp/bpp/main/keys.schema.json",
  "chrome": {
    "zip": "chromium.zip",
    "clientId": "123",
    "refreshToken": "789",
    "extId": "abcd"
  },
  "firefox": {
    "zip": "mozilla.zip",
    "extId": "123",
    "apiKey": "abcd",
    "apiSecret": "abcd"
  }
}
```

You can find instructions on how to get the keys in the schema, or in this [doc](https://github.com/plasmo-corp/bms/blob/main/tokens.md). If you use vscode, the schema should provide hint/intelisense when hovering over the json properties. If you need any help in setting up the keys, feel free to @ me! Otherwise if this doesn't seem necessary, feel free to close the PR :)

---

Side notes: [bpp](https://browser.market) is an open source action, together with its dependencies. You can audit the source 
 as well as providing any issue/feedback here:
- [Browser Plugin Publisher](https://github.com/plasmo-corp/bpp)
- [Browser Market Submit](https://github.com/plasmo-corp/bms)
- [Mozilla Webstore Upload](https://github.com/plasmo-corp/mwu)
- [Chrome Webstore Upload](https://github.com/plasmo-corp/cwu)

### CODE REVIEW

**Comment by pgamerx** [comment]
Thank you so much! I will review it once I get on my laptop

**Comment by pgamerx** [comment]
I have reviewed this, seems pretty good to me. 
But I have exams so I cannot do all the steps right now. 

My exams end on 16th March,2022, I will merge this then.
Thanks!

**Comment by louisgv** [comment]
Best of luck to your exam :D

**Comment by pgamerx** [comment]
Thanks

**Comment by pgamerx** [comment]
I finally have time to review this!

**Comment by louisgv** [comment]
Awesome! How was your final exams?  :D

**Comment by pgamerx** [comment]
They were good, and they weren't my finals lol

**Review by pgamerx — APPROVED** [review]

**Pull request merged**
