### PR TITLE
Used prettier to make the code consistent and look nicer

### PR DESCRIPTION
**Pull request by OfficialDelta**
Also removed a few </br> because that isn't valid html

### CODE REVIEW

**Comment by pgamerx** [comment]
This will break many things, It cannot be merged automatically so I will look into this

**Comment by davwheat** [comment]
The easier thing to do would be to install prettier, then set up a CI action to automatically run it on commits. That way there are no conflicts.

**Comment by pgamerx** [comment]
I'll look into it

**Comment by OfficialDelta** [comment]
the instructions for setting up a precommit hook are on prettier’s website 
```
npx mrm@2 lint-staged
```

the config i put in the repo is what i could make with your code style, feel free to change or mess around with it

**Comment by pgamerx** [comment]
Thanks, I will do this once I get on my PC

**Pull request closed without merging**
