### PR TITLE
Fix ratio bar

### PR DESCRIPTION
**Pull request by Adib-C**
Fixed ratio bar being too wide when there is a "Clip" button.

Changed the color of the ratio bar so that it matches the rest of youtube theme

### CODE REVIEW

**Comment by pgamerx** [comment]
Wait did you check it?

**Comment by Adib-C** [comment]
Check what

**Comment by pgamerx** [comment]
I meant test*

**Comment by Adib-C** [comment]
Of course i did

**Comment by Adib-C** [comment]
I wouldn't make a pull req if i haven't test it

**Pull request merged**
