### PR TITLE
fixed duplication code i had that caused a bug

### PR DESCRIPTION
**Pull request by thereaper90917**

### CODE REVIEW

**Comment by pgamerx** [comment]
Wait what

**Comment by thereaper90917** [comment]
had duplication of the progress bar i copied from the FF one and forgot about it XD it caused a bug in the chrome version

**Comment by pgamerx** [comment]
@thereaper90917 I think I didn't resolve the conflicts and just added both of them, how can I check 😩

**Comment by pgamerx** [comment]
Actually nevermind, I am merging

**Comment by thereaper90917** [comment]
yeah i am going merge the firefox one now its smaller but yeah sorry totally didn't see the bug until now

**Comment by pgamerx** [comment]
Oh alright. I just tested the chromium one and it works fine, I will have to test the ff version though before I'm ready for 1.7.5 on ff.

**Pull request merged**
